# Generated by Django 3.2.8 on 2022-04-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220411_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('surname', models.CharField(blank=True, max_length=55)),
                ('image', models.ImageField(blank=True, upload_to='singers')),
                ('info', models.TextField()),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
